name: Claude AI Workflow

on:
  issues:
    types: [opened, edited, labeled]
  issue_comment:
    types: [created]

jobs:
  claude-analysis:
      runs-on: ubuntu-latest
      if: contains(github.event.issue.body, '@claude') || contains(github.event.comment.body, '@claude')

      steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Claude AI 回應
          uses: anthropics/claude-code-action@beta
          with:
            anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}

        - name: Claude AI 呼叫成功通知
          if: always()
          run: echo "✅ Claude 回應觸發成功！"
  notify:
    runs-on: ubuntu-latest
    needs: [claude-analysis]
    if: always()
    
    steps:
    - name: Send notification
      run: |
        echo "Workflow completed"
        echo "Claude analysis status: ${{ needs.claude-analysis.result }}"
        echo "Build and test status: ${{ needs.build-and-test.result }}"
